import type { Metadata } from "next";
import { pretendard } from "@/config/font";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ViewTransition } from "react";
import { DialogService } from "@/components/reusable/dialog-service";
import { ReactQueryProvider } from "@/config/react-query/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.className} ${pretendard.variable} antialiased`}
      >
        <ViewTransition>
          <ReactQueryProvider>
            <NuqsAdapter>{children}</NuqsAdapter>
          </ReactQueryProvider>
        </ViewTransition>

        <DialogService />
      </body>
    </html>
  );
}
